### ISSUE TITLE
hydra error when running the train.py code

### ISSUE THREAD

**Issue by plentyluckman** [xuchen-ethz/snarf#5]
Hi, first of all , thanks for your team's great work.

I am having trouble running CAPE training code provided by readme.md

```console
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 266, in instantiate_node
    cfg[key] = instantiate_node(
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 245, in instantiate_node
    value = instantiate_node(
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
TypeError: Error instantiating 'lib.dataset.cape.CAPEDataProcessor' : __init__() missing 2 required positional arguments: 'opt' and 'meta_info'
```
and this msg is produced when I run
```console
 python train.py datamodule=cape subject=3375 +datamodule.clothing='blazerlong' +experiments=cape  
```
I put + right before datamodule.clothing argument on purpose, which is different from the guide on readme.md; otherwise, it gave different error like:
```console
omegaconf.errors.ConfigAttributeError: Key 'clothing' is not in struct
    full_key: datamodule.clothing
    object_type=dict
```

I think **datamodule = hydra.utils.instantiate(opt.datamodule, opt.datamodule)** in train.py part gave this error.

If I train on AMASS it also produces similar error

```console
python train.py subject=50002
```

then
```console

Traceback (most recent call last):
  File "D:\python_proj\snarf\train.py", line 64, in <module>
    main()
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\main.py", line 48, in decorated_main
    _run_hydra(
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\utils.py", line 377, in _run_hydra
    run_and_report(
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\utils.py", line 214, in run_and_report
    raise ex
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\utils.py", line 211, in run_and_report
    return func()
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\hydra.py", line 111, in run
    _ = ret.return_value
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\core\utils.py", line 233, in return_value
    raise self._return_value
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\core\utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "D:\python_proj\snarf\train.py", line 22, in main
    datamodule = hydra.utils.instantiate(opt.datamodule, opt.datamodule) #problem starts here.
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 266, in instantiate_node
    cfg[key] = instantiate_node(
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "C:\Users\mms312\anaconda3\envs\snarf_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
TypeError: Error instantiating 'lib.dataset.dfaust.DFaustDataModule' : __init__() missing 1 required positional argument: 'opt'
```

Any thought or idea on this?
Thanks,

**Comment by xuchen-ethz** [comment]
Hi @plentyluckman,

it could be caused by different hydra versions - hydra API changes very quickly. 

Could you let me know which version of hydra are you currently using? Also if it's not hydra-core==1.0.6, could you try 1.0.6 instead?

**Comment by plentyluckman** [comment]
@xuchen-ethz 

yes, you are right.
The error not showing up anymore, after downgrading the hydra-core version (from 1.1.0 to 1.0.6)

Thank you

**Comment by xuchen-ethz** [comment]
great :)
